/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Producto;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;

/**
 *
 * @author Gerson
 */
public class JInternalFrameProducto extends javax.swing.JInternalFrame {
    /**Arreglo de objetos productos*/
    ArrayList<Producto> listaProducto=new ArrayList<>();
    int índice=-1;
    /**
     * Creates new form JInternalFrameProducto
     */
   public JInternalFrameProducto() { 
        initComponents();
    }
private void limpiarCampos(){ //Método para limpiar cajas de texto
    //Se asigna un valor vacío a todas las cajas de texto
    //Se utiliza el nombre de variable asignado
    this.jTextFieldNombre.setText(""); // Set es para asignar un valor
    this.jTextFieldCategoria.setText ("");
    this.jTextFieldPrecio.setText ("");
    this.jTextFieldExistencia.setText ("");
}
    private void llenarTabla(){
      DefaultTableModel modelo = new DefaultTableModel();
      String[] columnas = {"Nombres", "Categoría",
            "Precio","Existencia"};
       modelo.setColumnIdentifiers(columnas);
        for(Producto pro: listaProducto){
             String[] renglon = {pro.getNombre(),
               pro.getCategoría(),Double.toString(pro.getPrecio()),
               Integer.toString(pro.getExistencia())};
            modelo.addRow(renglon);
        }
        jTableProductos.setModel(modelo);
     
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldExistencia = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCategoria = new javax.swing.JTextField();

        jMenuItem1.setText("Enviar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Precio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Existencia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, -1));

        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 210, -1));

        jTextFieldExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 210, -1));

        jButtonGuardar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jButtonLimpiar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jButtonEliminar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Precio", "Existencia"
            }
        ));
        jTableProductos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(3).setHeaderValue("Existencia");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 230, 160));

        jButtonEditar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jButtonActualizar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonActualizar.setText("Actulizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Datos de producto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 60));

        jTextFieldCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
         if((jTextFieldNombre.getText().contentEquals(""))||
              (jTextFieldCategoria.getText().contentEquals("")) ||
              (jTextFieldPrecio.getText().contentEquals("")) ||
              (jTextFieldExistencia.getText().contentEquals(""))) {
          llenarTabla();
          
       JOptionPane.showMessageDialog(null,
                    "Algunos campos estan vacíos",
                        "¡Revise todos los campos!",
                        JOptionPane.WARNING_MESSAGE);
                 
            }else{    
                //Get para obtener un valor    
        String nombreProducto=this.jTextFieldNombre.getText();
        String nombreCategoria=this.jTextFieldCategoria.getText();
        //Obtiene lo que la caja de texto y convierte a tipo de dato
        double precioProducto=Double.parseDouble(this.jTextFieldPrecio.getText());
        int existenciaProducto=Integer.parseInt(this.jTextFieldExistencia.getText());
                
                
            try{ //Bloque try (intentar) - catch (capturar) para capturar errores
              //Declarando un objeto de la clase Producto,
              //Crea un objeto de clase Producto
              //LLama al método constructor de la clase Producto
             Producto prod=new Producto(nombreProducto,nombreCategoria,
                     precioProducto, existenciaProducto);
             this.listaProducto.add(prod);
               
             this.limpiarCampos();//Llamar al método limpiar campos
             llenarTabla();
             
             JOptionPane.showMessageDialog(null,
                     "Datos agregados correctamente");

        }catch(Exception e){     
            JOptionPane.showConfirmDialog(null,
                    "Datos no agregados","Error",
                    JOptionPane.ERROR_MESSAGE);
        }      
       }        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExistenciaActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
     limpiarCampos();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int fila = this.jTableProductos.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(rootPane,
                "Seleccione un registro de la tabla");

        } else {
            JDialog.setDefaultLookAndFeelDecorated(true);
            int resp = JOptionPane.showConfirmDialog(null,
                "Estas seguro de eliminar?","Eliminando...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(resp==JOptionPane.YES_NO_OPTION) {
                listaProducto.remove(fila);
                llenarTabla();      
        }
     }   
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int fila = this.jTableProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane,
                      "Seleccione un registro de la tabla");
        } else {
            String nom = (String) this.jTableProductos.getValueAt(fila,0);
            String cat = (String) this.jTableProductos.getValueAt(fila,1);
            double prec =Double.parseDouble((String) this.jTableProductos.getValueAt(fila,2));
            int exis =Integer.parseInt((String) this.jTableProductos.getValueAt(fila,3));
            jTextFieldNombre.setText(nom);
            jTextFieldCategoria.setText(cat);
            jTextFieldPrecio.setText(String.valueOf(prec));
            jTextFieldExistencia.setText(String.valueOf(exis));
            índice=fila;
            }       
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
      if((jTextFieldNombre.getText().contentEquals(""))||
        (jTextFieldCategoria.getText().contentEquals(""))||
        (jTextFieldPrecio.getText().contentEquals(""))||     
        (jTextFieldExistencia.getText().contentEquals(""))||índice==-1){
        JOptionPane.showMessageDialog(null,
                    "Algunos campos estan vacíos,seleccione de la tabla de datos",
                    "Actualizar...",
                    JOptionPane.WARNING_MESSAGE);
        limpiarCampos();
        
        }else{
          listaProducto.get(índice).setNombre(jTextFieldNombre.getText());
          listaProducto.get(índice).setCategoría(jTextFieldCategoria.getText()); 
          listaProducto.get(índice).setPrecio(Double.valueOf(jTextFieldPrecio.getText()));
          listaProducto.get(índice).setExistencia
                  (Integer.parseInt(jTextFieldExistencia.getText()));
          llenarTabla();
          limpiarCampos();        
      }
        
        
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextFieldCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategoriaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldExistencia;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}