/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Ventas;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.JTextField;
/**
 *
 * @author Usuario
 */
public class NewJInternalFrameVentas extends javax.swing.JInternalFrame {

    ArrayList<Ventas>listaVentas=new ArrayList<>();
      int índice=-1;
    /**
     * Creates new form NewJInternalFrameVentas
     */
    public NewJInternalFrameVentas() {
        initComponents();
    }
    
private void limpiarCampos(){ //Método para limpiar cajas de texto
    //Se asigna un valor vacío a todas las cajas de texto
    //Se utiliza el nombre de variable asignado
    this.jTextFieldNombreV.setText(""); // Set es para asignar un valor
    this.jTextFieldPrecioV.setText ("");
    this.jTextFieldCantidadV.setText ("");
    this.jTextFieldSobrante.setText ("");
    this.jTextFieldFechaV.setText("");
}
  private void llenarTabla(){
      DefaultTableModel modelo = new DefaultTableModel();
      String[] columnas = {"Nombres", "Precio",
            "Cantidad vendida","Cantidad sobrante","Fecha Venta:"};
      
       modelo.setColumnIdentifiers(columnas);
       
        for(Ventas Ven: listaVentas){
             String[] renglon = {Ven.getNombreV(),
                 
              
               Double.toString(Ven.getPrecioV()),Integer.toString(Ven.getCantidadV()),
               Integer.toString(Ven.getSobrante()),Ven.getFechaV()};
             
            modelo.addRow(renglon);
        }
         jTableVentas.setModel(modelo);
        }  
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNombreV = new javax.swing.JTextField();
        jTextFieldPrecioV = new javax.swing.JTextField();
        jTextFieldCantidadV = new javax.swing.JTextField();
        jTextFieldSobrante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFechaV = new javax.swing.JTextField();
        jButtonGuardarV = new javax.swing.JButton();
        jButtonEliminarV = new javax.swing.JButton();
        jButtonEditarV = new javax.swing.JButton();
        jButtonActualizarV = new javax.swing.JButton();
        jButtonLimpiarV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar venta");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jTextFieldPrecioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioVActionPerformed(evt);
            }
        });

        jTextFieldSobrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSobranteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad vendida");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad sobrante");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Fecha Venta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrecioV, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreV)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFechaV)
                            .addComponent(jTextFieldCantidadV, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jTextFieldSobrante))))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCantidadV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSobrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonGuardarV.setBackground(new java.awt.Color(204, 255, 204));
        jButtonGuardarV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardarV.setForeground(new java.awt.Color(0, 204, 102));
        jButtonGuardarV.setText("Guardar");
        jButtonGuardarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarVActionPerformed(evt);
            }
        });

        jButtonEliminarV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEliminarV.setForeground(new java.awt.Color(204, 0, 0));
        jButtonEliminarV.setText("Eliminar");
        jButtonEliminarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarVActionPerformed(evt);
            }
        });

        jButtonEditarV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEditarV.setText("Editar");
        jButtonEditarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarVActionPerformed(evt);
            }
        });

        jButtonActualizarV.setBackground(new java.awt.Color(204, 255, 204));
        jButtonActualizarV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonActualizarV.setText("Actualizar");

        jButtonLimpiarV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLimpiarV.setText("Limpiar");
        jButtonLimpiarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarVActionPerformed(evt);
            }
        });

        jTableVentas.setBackground(new java.awt.Color(204, 204, 255));
        jTableVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha Venta", "Cantidad", "Cantidad restante", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTableVentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButtonLimpiarV)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonEliminarV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonEditarV)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonActualizarV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonGuardarV)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardarV)
                            .addComponent(jButtonEditarV)
                            .addComponent(jButtonActualizarV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEliminarV)
                            .addComponent(jButtonLimpiarV))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarVActionPerformed
        if((jTextFieldNombreV.getText().contentEquals(""))||
              (jTextFieldCantidadV.getText().contentEquals(""))||
              (jTextFieldPrecioV.getText().contentEquals(""))||
              (jTextFieldSobrante.getText().contentEquals(""))||
              (jTextFieldFechaV.getText().contentEquals("")))
        {
              
             llenarTabla();
            JOptionPane.showConfirmDialog(null,
                   "Algunos campos estan vacíos",
                   "Revise todos los campos!",
                    JOptionPane.WARNING_MESSAGE);
                
        }else{
        String NombreVentas=this.jTextFieldNombreV.getText();  
        double PrecioVentas=Double.parseDouble(this.jTextFieldPrecioV.getText());
        int CantidadVendida=Integer.parseInt(this.jTextFieldCantidadV.getText());
        int CantidadSobrante=Integer.parseInt(this.jTextFieldSobrante.getText());
        String FechaVenta=this.jTextFieldFechaV.getText();
            try{
        
       Ventas vent=new Ventas(NombreVentas,PrecioVentas,
             CantidadVendida,CantidadSobrante,FechaVenta);      
        this.listaVentas.add(vent);
         this.limpiarCampos(); 
         llenarTabla();
        JOptionPane.showMessageDialog(null,
                "Datos agregados correctamente");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null,
              "Datos no agregados","Error",
               JOptionPane.ERROR_MESSAGE);
              
        }  
        }
                   
                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarVActionPerformed

    private void jButtonLimpiarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarVActionPerformed
    limpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarVActionPerformed

    private void jTextFieldPrecioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioVActionPerformed

    private void jTextFieldSobranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSobranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSobranteActionPerformed

    private void jButtonEliminarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarVActionPerformed
 int fila = this.jTableVentas.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(rootPane,
                "Seleccione un registro de la tabla");

        } else {
            JDialog.setDefaultLookAndFeelDecorated(true);
            int resp = JOptionPane.showConfirmDialog(null,
                "Estas seguro de eliminar?","Eliminando...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(resp==JOptionPane.YES_NO_OPTION) {
                listaVentas.remove(fila);
                llenarTabla();      
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarVActionPerformed

    private void jButtonEditarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarVActionPerformed
         int fila = this.jTableVentas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane,
                      "Seleccione un registro de la tabla");
        } else {
            String nom = (String) this.jTableVentas.getValueAt(fila,0);
            String cat = (String) this.jTableVentas.getValueAt(fila,1);
            double prec =Double.parseDouble((String) this.jTableVentas.getValueAt(fila,2));
            int sob =Integer.parseInt((String) this.jTableVentas.getValueAt(fila,3));
            String Fech = (String) this.jTableVentas.getValueAt(fila,4);
            jTextFieldNombreV.setText(nom);
            jTextFieldPrecioV.setText(String.valueOf(prec));
            jTextFieldCantidadV.setText(String.valueOf(cat));
            jTextFieldSobrante.setText(String.valueOf(sob));
            jTextFieldFechaV.setText(Fech);
              índice=fila;
        }
    }//GEN-LAST:event_jButtonEditarVActionPerformed

    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarV;
    private javax.swing.JButton jButtonEditarV;
    private javax.swing.JButton jButtonEliminarV;
    private javax.swing.JButton jButtonGuardarV;
    private javax.swing.JButton jButtonLimpiarV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextFieldCantidadV;
    private javax.swing.JTextField jTextFieldFechaV;
    private javax.swing.JTextField jTextFieldNombreV;
    private javax.swing.JTextField jTextFieldPrecioV;
    private javax.swing.JTextField jTextFieldSobrante;
    // End of variables declaration//GEN-END:variables
}
